const en = {
  common: {
    next: 'Next',
    somethingWentWrongMessage: 'Something went wrong.',
    vip: 'VIP',
    agent: 'Agent',
    brand: 'Brand',
    search: 'Search',
    noResult: 'No results found.',
    cancel: 'Cancel',
    yes: 'Yes',
    ok: 'OK',
  },
  helperText: {
    noAccount: "Don't have an account?",
    continue: 'Continue',
    loading: 'Loading...',
    applyHere: 'Apply here',
  },
  nav: {
    home: 'Home',
    opportunities: 'Opportunities',
    event: 'Event',
    message: 'Message',
    basket: 'Basket',
    myOrders: 'My Orders',
    myProfile: 'My Profile',
    homeTitles: {
      featured: 'Featured',
      opportunities: 'Opportunities',
      byRequest: 'By Request',
      featureEvent: 'Featured Event',
      searchAnything: 'Search anything...',
      welcome: 'Welcome',
    },
  },
  signUpOptions: {
    applyAs: 'Apply as',
    asVIP: 'As VIP',
    asBrand: 'As Brand',
    asAgent: 'As Agent',
    loginTxt: 'Log in here',
  },
  login: {
    placeholder: {
      email: 'Email',
      password: 'Password',
      continue: 'Continue',
      noAccountExist: 'No account? Apply here.',
      applyHereButton: 'Apply here',
      secondaryEmail: 'Secondary Email',
      resetPassword: 'Reset Password',
      verifyCode: 'Verification Code',
      newPassword: 'New Password',
      savePassword: 'Save Password',
      repeatPassword: 'Repeat Password',
    },
    errorMessage: {
      email: 'Invalid email address.',
      requiredEmail: 'Email is required.',
      password: 'Invalid password.',
      requiredPassword: 'Password is required.',
      codeLength: 'Code must be 6 characters.',
      requiredCode: 'Verification code is required.',
      invalidPassword: 'Invalid password format.',
      repeatPasswordRequired: 'Repeat password is required.',
      passwordMustMatch: 'Passwords must match.',
    },
    forgotPassword: {
      forgotPass: 'Forgot Password?',
      subTitle: 'Enter your email to reset your password.',
      backToLogin: 'Back to login',
      codeSent: 'Verification code sent.',
    },
  },
  customReviewScreen: {
    thankyou: 'Thank you!',
    inReview: 'Application in review.',
    description:
      'Thank you for your application. The concierge team will review your submission and will be in touch in due course with their decision.',
    done: 'Done',
  },
  customBrandReviewScreen: {
    thankyou: 'Thank you!',
    inReview: 'We’ll be in touch',
    description:
      'Thank you for your application. The concierge team will review your submission and will be in touch in due course.',
    done: 'Done',
  },
  customAcceptedScreen: {
    acceptedTxt: 'Application Accepted!',
    welcomeTxt: 'Welcome',
    welcomePara: 'You are now welcome to create an account. Please continue to complete your profile.',
    continue: 'Continue',
    agentWelcomePara: 'As an agent, explore new opportunities.',
  },
  customBrandAcceptedScreen: {
    acceptedTxt: 'Welcome!',
    welcomeTxt: 'Glad to have you',
    welcomePara: 'You can now build your brand profile.',
    continue: 'Continue',
  },
  customRejectedScreen: {
    rejectedTxt: 'Application Rejected!',
    subTitle: 'Unfortunately!',
    rejectedPara:
      'Your account application for VIP Suite has been reviewed and rejected. If you believe this decision was made in error or have questions, please feel free to contact our support team for further clarification.',
    continue: 'Continue',
    logoutText: 'Press OK to log out and exit the app.',
  },
  customProfileInReviewScreen: {
    thankyou: 'Thank you!',
    inReview: 'Profile in review.',
    inReviewPara:
      'Thanks for completing your profile. Your profile will be moderated and we will contact you once your profile has been verified.',
    inReviewSubPara: 'You can update your profile at any time.',
    done: 'Done',
  },
  addedVipStatusScreen: {
    thankyou: 'Thank you!',
    title: 'VIP Added',
    vipAddedTitle: 'Thanks for adding a VIP. You can update your VIP’s profile at any time.',
    addAnotherTitle: 'Would you like to add another VIP?',
    addAnotherVIP: 'Add Another VIP',
    continue: 'Continue',
  },
  profileBuilder: {
    knownForScreen: {
      title: 'What are you known for?',
      subTitle: 'Select your expertise.',
    },
    additionalContact: {
      heading: {
        additionalContacts: 'Additional Contacts',
        contactMeDirectly: 'Contact Me Directly',
      },
      event: {
        title: 'Event Contact',
        paragraph: 'Reach me for event opportunities.',
      },
      stylist: {
        title: 'Stylist Contact',
        paragraph: 'Available for styling services.',
      },
      commercialOpportunities: {
        title: 'commercialOpportunities Contact',
        paragraph: 'Reach out for commercial Opportunities collaborations.',
      },
      errorMessage: {
        email: 'Invalid email.',
        requiredEmail: 'Email is required.',
        secondaryEmail: 'Invalid secondary email.',
      },
    },
    yourDetails: {
      title: 'Your Details',
      placeholder: {
        dob: 'Date of Birth',
        birthplace: 'Birthplace',
        nationality: 'Nationality',
        ethnicity: 'Ethnicity',
        numberOfChild: 'Number of Children',
        childInfo: 'Child Information',
        gender: 'Gender',
        pets: 'Pets',
        homePostcode: 'Home Postcode',
        childInfoTitle: 'Child Information',
        child: 'Child',
      },
      hint: {
        postCodeHint: 'Enter your postal code.',
        petsHint: 'List your pets.',
      },
      errorMessage: {
        dob: 'DOB is required.',
        birthplace: 'Birthplace is required.',
        nationality: 'Nationality is required.',
        ethnicity: 'Ethnicity is required.',
        child: 'Enter child details.',
        ageOfChild: "Enter child's age.",
        genderOfChild: "Select child's gender.",
        pets: 'Please select a pet.',
        homePostcode: 'Invalid postal code. Please enter a valid postal code.',
      },
    },
    typeOfContent: {
      errorMessage: {
        otherSports: 'Specify other sports.',
        sportsPlay: 'Specify sports you play.',
        sportsFollow: 'Specify sports you follow.',
        skills: 'Enter your skills.',
        lookFeelOfSocials: 'Describe your social media presence.',
        contentType: 'Specify content type.',
      },
    },
    addVip: {
      title: 'Add VIP',
      vipDetails: 'VIP Details',
      placeholder: {
        firstName: 'First Name',
        lastName: 'Last Name',
        representationType: 'Representation Type',
        instagram: 'Instagram Handle',
        tiktok: 'TikTok Handle',
        engagement: 'Average Engagement',
      },
      errorMessage: {
        firstName: 'First name is required.',
        lastName: 'Last name is required.',
        representationType: 'Specify representation type.',
        instagram: 'Invalid Instagram handle.',
        tiktok: 'Invalid TikTok handle.',
        engagement: 'Invalid engagement rate.',
      },
      avgEngagementHeading: 'Average Engagement Rate',
      avgEngagementSubheading: 'Enter engagement details.',
    },
  },
  applyAndSignin: {
    apply: 'Apply',
    signin: 'Sign In',
  },
  address: {
    errorMessage: {
      addressLineOneRequired: 'Address line 1 is required.',
      addressLineTwoRequired: 'Address line 2 is required.',
      cityRequired: 'City is required.',
      postcodeRequired: 'Invalid postal code. Please enter a valid postal code.',
      stateRequired: 'State is required.',
      countryRequired: 'Country is required.',
    },
  },
  signup: {
    placeholder: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      password: 'Password',
      secondaryEmail: 'Secondary Email',
      phone: 'Phone',
      instagram: 'Instagram Handle',
      tiktok: 'TikTok Handle',
      continue: 'Continue',
      companyName: 'Company Name',
      typeOfRepresentation: 'Type of Representation',
      exampleOfVIP: 'Example of VIPs',
      brandName: 'Brand Name',
      contactName: 'Contact Name',
      typeOfBusiness: 'Type of Business',
      sportsPlay: 'Sports You Play',
      otherSport: 'Other Sports',
      sportsFollow: 'Sports You Follow',
      skills: 'Skills',
      lookFeelOfSocials: 'Look and Feel of Socials',
      contentType: 'Content Type',
      agenciesType: 'Agency Type',
      brandType: 'Brand Type',
    },
    label: {
      brandTitle: 'Brand',
      vipTitle: 'VIP',
      agentTitle: 'Agent',
      subTitle: 'Tell us more about yourself.',
      addStaff: 'Add Staff',
      optional: 'Optional',
      includingCode: 'Including Code',
      addVip: 'Add VIP',
    },
    errorMessage: {
      firstName: 'First Name must be at least 3 characters long',
      lastName: 'Last Name must be at least 3 characters long',
      firstNameRequired: 'First name is required.',
      lastNameRequired: 'Last name is required.',
      email: 'Email is required.',
      requiredEmail: 'Invalid email.',
      password: 'Invalid password.',
      phoneValidation: 'Please enter a valid phone number.',
      passwordValidation:
        'The password must be a minimum of 6 characters long and include at least one uppercase, one lowercase letter, one number, and one special character.',
      requiredPassword: 'Password is required.',
      phone: 'Please enter a valid phone number.',
      instagram: 'Invalid Instagram handle.',
      tiktok: 'Invalid TikTok handle.',
      instagramRequired: 'Instagram handle is required.',
      tiktokRequired: 'TikTok handle is required.',
      instagramInvalid: 'Invalid Instagram handle.',
      tiktokInvalid: 'Invalid TikTok handle.',
      companyName: 'Company name is required.',
      typeRepresentation: 'Specify representation type.',
      exampleOfVip: 'Provide examples of VIPs.',
      brandName: 'Brand name is required.',
      contactName: 'Contact name is required.',
      typeOfBusiness: 'Specify type of business.',
      selectedCategory: 'Select a category.',
      phoneErrorMessage: 'Please enter a valid phone number.',
      passMatch: 'Passwords must match.',
      agencyType: 'Specify agency type.',
      brandType: 'Specify brand type.',
      code: 'Reset code is required',
    },
  },
  listEmptyMessage: {
    emptyBasket: 'This space is empty, Fill it with something amazing!',
    noData: 'Check Back Soon',
    noItems: 'No Items Available',
    addItemMessage: 'Start Adding And Come Back',
    noHomeData: 'Items',
    noVipListData: 'No VIPs Available',
    noVipDataMessage: 'Start adding and Come Back',
    noCartData: 'Items',
    noCartDataMessage: 'Start adding and Come Back',
    noEventData: 'No Events Available',
    noOrderData: 'No Orders Available',
    noMessageData: 'No Messages Available',
    noProductData: 'No Products Available',
    noOpportunityData: 'No Opportunities Available',
    noBioData: 'Bio',
    noContactData: 'No Contacts Available',
    noContactDataMessage: 'Update Profile And Come Back',
    noSocialData: 'Social Handles',
    noAddressData: 'No Address Available',
  },

  landingForm: {
    placeholder: {
      role: 'Brand, VIP or Agent?',
      name: 'Name',
      email: 'Email',
      jobTitle: 'Job Title',
      companyName: 'Company Name',
      phone: 'Phone',
    },
    errorMessage: {
      roleRequired: 'Select a Role.',
      nameRequired: 'Name is required.',
      emailRequired: 'Email is required.',
      companyRequired: 'Company Name is required.',
      jobTitleRequired: 'Job Title is required.',
      phoneValidation: 'Please enter a valid phone number, including the country code with + sign.',
    },
  },
};

export default en;
