const en = {
  common: {
    next: 'Next',
    somethingWentWrongMessage: 'Something went wrong.',
    vip: 'VIP',
    agent: 'Agent',
    brand: 'Brand',
    search: 'Search',
    noResult: 'No results found.',
    cancel: 'Cancel',
    yes: 'Yes',
    nonceNotFound: 'Nonce not found.',
    ok: 'OK',
  },
  nav: {
    home: 'Home',
    opportunities: 'Opportunities',
    event: 'Event',
    message: 'Message',
    basket: 'Basket',
    myOrders: 'My Orders',
    myProfile: 'My Profile',
    homeTitles: {
      featured: 'Featured',
      opportunities: 'Opportunities',
      byRequest: 'By Request',
      featureEvent: 'Featured Event',
      searchAnything: 'Search anything...',
      welcome: 'Welcome',
    },
  },
  signUpOptions: {
    applyAs: 'Apply as',
    asVIP: 'As VIP',
    asBrand: 'As Brand',
    asAgent: 'As Agent',
    loginTxt: 'Log in here',
  },
  login: {
    placeholder: {
      email: 'Email',
      password: 'Password',
      continue: 'Continue',
      noAccountExist: 'No account? Apply here.',
      applyHereButton: 'Apply here',
      secondaryEmail: 'Secondary Email',
      resetPassword: 'Reset Password',
      verifyCode: 'Verification Code',
      newPassword: 'New Password',
      savePassword: 'Save Password',
      repeatPassword: 'Repeat Password',
    },
    errorMessage: {
      email: 'Invalid email address.',
      requiredEmail: 'Email is required.',
      password: 'Invalid password.',
      requiredPassword: 'Password is required.',
      codeLength: 'Code must be 6 characters.',
      requiredCode: 'Verification code is required.',
      invalidPassword: 'Invalid password format.',
      repeatPasswordRequired: 'Repeat password is required.',
      passwordMustMatch: 'Passwords must match.',
    },
    forgotPassword: {
      forgotPass: 'Forgot Password?',
      subTitle: 'Enter your email to reset your password.',
      backToLogin: 'Back to login',
      codeSent: 'Verification code sent.',
    },
  },
  customReviewScreen: {
    thankyou: 'Thank you!',
    inReview: 'Your application is in review.',
    thankyouPara: 'We appreciate your patience.',
    done: 'Done',
  },
  customAcceptedScreen: {
    acceptedTxt: 'Congratulations!',
    welcomeTxt: 'Welcome onboard.',
    welcomePara: 'We are excited to have you.',
    continue: 'Continue',
    agentWelcomePara: 'As an agent, explore new opportunities.',
  },
  customRejectedScreen: {
    rejectedTxt: 'Application Rejected',
    subTitle: 'We appreciate your interest.',
    rejectedPara: 'Feel free to reapply later.',
    continue: 'Continue',
    logoutText: 'Logout',
  },
  customProfileInReviewScreen: {
    thankyou: 'Thank you!',
    inReview: 'Profile in review.',
    inReviewPara: 'We are processing your information.',
    inReviewSubPara: 'You will hear from us soon.',
    done: 'Done',
  },
  addedVipStatusScreen: {
    title: 'VIP Added',
    thankyou: 'Thank you!',
    vipAddedTitle: 'VIP status successfully added.',
    thanksForAddingPara: 'Thank you for adding a VIP.',
    addAnotherVIP: 'Add Another VIP',
    continue: 'Continue',
    pendingMessage: 'Pending approval.',
    rejectedMessage: 'Application rejected.',
    accountStatusLabel: 'Account Status',
  },
  profileBuilder: {
    knownForScreen: {
      title: 'What are you known for?',
      subTitle: 'Select your expertise.',
    },
    additionalContact: {
      heading: {
        additionalContacts: 'Additional Contacts',
        contactMeDirectly: 'Contact Me Directly',
      },
      event: {
        title: 'Event Contact',
        paragraph: 'Reach me for event opportunities.',
      },
      stylist: {
        title: 'Stylist Contact',
        paragraph: 'Available for styling services.',
      },
      commercialOpportunities: {
        title: 'commercialOpportunities Contact',
        paragraph: 'Reach out for commercial Opportunities collaborations.',
      },
      errorMessage: {
        email: 'Invalid email.',
        requiredEmail: 'Email is required.',
        secondaryEmail: 'Invalid secondary email.',
      },
    },
    yourDetails: {
      title: 'Your Details',
      placeholder: {
        dob: 'Date of Birth',
        birthplace: 'Birthplace',
        nationality: 'Nationality',
        ethnicity: 'Ethnicity',
        numberOfChild: 'Number of Children',
        childInfo: 'Child Information',
        gender: 'Gender',
        pets: 'Pets',
        homePostcode: 'Home Postcode',
        childInfoTitle: 'Child Information',
        child: 'Child',
      },
      hint: {
        postCodeHint: 'Enter your postal code.',
        petsHint: 'List your pets.',
      },
      errorMessage: {
        dob: 'Invalid date of birth.',
        birthplace: 'Birthplace is required.',
        nationality: 'Nationality is required.',
        ethnicity: 'Ethnicity is required.',
        child: 'Enter child details.',
        ageOfChild: "Enter child's age.",
        pets: 'Invalid pet details.',
        homePostcode: 'Invalid postcode.',
      },
    },
    typeOfContent: {
      errorMessage: {
        selectedCategory: 'Select a category.',
        sportsPlay: 'Specify sports you play.',
        sportsFollow: 'Specify sports you follow.',
        skills: 'Enter your skills.',
        lookFeelOfSocials: 'Describe your social media presence.',
        contentType: 'Specify content type.',
      },
    },
    addVip: {
      title: 'Add VIP',
      vipDetails: 'VIP Details',
      placeholder: {
        firstName: 'First Name',
        lastName: 'Last Name',
        representationType: 'Representation Type',
        instagram: 'Instagram Handle',
        tiktok: 'TikTok Handle',
        engagement: 'Average Engagement',
      },
      errorMessage: {
        firstName: 'First name is required.',
        lastName: 'Last name is required.',
        representationType: 'Specify representation type.',
        instagram: 'Invalid Instagram handle.',
        tiktok: 'Invalid TikTok handle.',
        engagement: 'Invalid engagement rate.',
      },
      avgEngagementHeading: 'Average Engagement Rate',
      avgEngagementSubheading: 'Enter engagement details.',
    },
  },
  applyAndSignin: {
    apply: 'Apply',
    signin: 'Sign In',
  },
  signup: {
    placeholder: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      password: 'Password',
      secondaryEmail: 'Secondary Email',
      phone: 'Phone',
      instagram: 'Instagram Handle',
      tiktok: 'TikTok Handle',
      continue: 'Continue',
      companyName: 'Company Name',
      typeOfRepresentation: 'Type of Representation',
      exampleOfVIP: 'Example of VIPs',
      brandName: 'Brand Name',
      contactName: 'Contact Name',
      typeOfBusiness: 'Type of Business',
      sportsPlay: 'Sports You Play',
      otherSport: 'Other Sports',
      sportsFollow: 'Sports You Follow',
      skills: 'Skills',
      lookFeelOfSocials: 'Look and Feel of Socials',
      contentType: 'Content Type',
      agenciesType: 'Agency Type',
      brandType: 'Brand Type',
    },
    label: {
      brandTitle: 'Brand',
      vipTitle: 'VIP',
      agentTitle: 'Agent',
      subTitle: 'Tell us more about yourself.',
      addStaff: 'Add Staff',
      optional: 'Optional',
      includingCode: 'Including Code',
      addVip: 'Add VIP',
    },
    errorMessage: {
      firstName: 'First name is required.',
      lastName: 'Last name is required.',
      email: 'Invalid email.',
      requiredEmail: 'Email is required.',
      password: 'Invalid password.',
      requiredPassword: 'Password is required.',
      phone: 'Invalid phone number.',
      instagram: 'Invalid Instagram handle.',
      tiktok: 'Invalid TikTok handle.',
      companyName: 'Company name is required.',
      typeRepresentation: 'Specify representation type.',
      exampleOfVip: 'Provide examples of VIPs.',
      brandName: 'Brand name is required.',
      contactName: 'Contact name is required.',
      typeOfBusiness: 'Specify type of business.',
      selectedCategory: 'Select a category.',
      phoneErrorMessage: 'Invalid phone number.',
      passMatch: 'Passwords must match.',
      agencyType: 'Specify agency type.',
      brandType: 'Specify brand type.',
    },
  },
};

export default en;
