const Endpoints = {
  login: '/wp/v2/login',
  vipSignup: '/wp/v2/signup/vip',
  agentSignup: '/wp/v2/signup/agent',
  getProfile: '/wp/v2/users/me',
  getBrands: '/wp/v2/brand-profiles',
  getDashboardContent: '/wp/v2/vip-profiles/dashboard-content',
  getBrandDetails: (brandId: number) => `/wp/v2/brand-profiles/${brandId}`,
  getBrandProducts: (brandId: number) => `/wc/v3/products?brand_profile_id=${brandId}`,
  getBrandProductDetails: (productId: number) => `/wc/v3/products/${productId}`,
  getSignupContent: '/wp/v2/signup-content',
  getVipEvents: '/wp/v2/events',
  getVipEventDetails: (id: number) => `/wp/v2/events/${id}`,
  getProfileBuilderContent: '/wp/v2/profile-builder-content',
  updateProfile: '/wp/v2/vip-profile',
  forgotPassword: ' /wp/v2/forgot-password',
  resetPassword: '/wp/v2/reset-password',
  getAllOrders: (customerId: number) => `/wc/v3/orders?customer=${customerId}`,
  getOrderById: (id: number) => `/wc/v3/orders/${id}`,
  getVipCart: '/wc/store/v1/cart',
  addItemToCart: '/wc/store/v1/cart/add-item',
  removeVipCartItem: (key: string) => `/wc/store/v1/cart/remove-item?key=${key}`,
  removeAllCartItems: `/wc/store/v1/cart/items`,
  createOrder: `/wc/v3/orders`,
  getVipOpportunities: '/wp/v2/opportunities?_fields=id,title,opportunity-category,acf.featured_image,is_wishlisted',
  sendRsvp: '/wp/v2/rsvp-request',
  logOut: '/wp/v2/logout',
  getVipRsvpEvents: `/wp/v2/vip-profiles/rsvp-events`,
  getAddresses: '/wp/v2/vip-profiles/addresses',
  deleteAddress: (addressId: number) => `/wp/v2/vip-profiles/addresses/${addressId}`,
  getVipOpportunityDetails: '/wp/v2/opportunities',
  orderFeedback: (orderNumber: number) => `/wp/v2/vip-profiles/orders/${orderNumber}/feedback`,
  eventFeedback: (eventId: number) => `/wp/v2/vip-profiles/events/${eventId}/feedback`,
  getWishlistItems: `/wp/v2/vip-profiles/wishlist`,
  addToWishlist: (postId: number) => `/wp/v2/vip-profiles/wishlist/${postId}`,
  referVIP: '/wp/v2/vip-profiles/refer-vip',
};

export { Endpoints };
