const Endpoints = {
  login: '/wp/v2/login',
  vipSignup: '/wp/v2/signup/vip',
  agentSignup: '/wp/v2/signup/agent',
  getProfile: '/wp/v2/users/me',
  getBrands: '/wp/v2/brand-profiles',
  getBrandDetails: '/wp/v2/brand-profiles',
  getBrandProducts: (id: number) => `/wc/v3/products?brand_profile_id=${id}`,
  getBrandProductDetails: '/wc/v3/products',
  getSignupContent: '/wp/v2/signup-content',
  getVipEvents: '/wp/v2/events',
  getVipEventDetails: '/wp/v2/events',
  getProfileBuilderContent: '/wp/v2/profile-builder-content',
  updateProfile: '/wp/v2/vip-profile',
  forgotPassword: '/wp/v2/password-forgot',
  resetPassword: 'wp/v2/password-reset',
  getAllOrders: (customerId: number) => `/wc/v3/orders?customer=${customerId}`,
  getOrderById: '/wc/v3/orders',
  getVipCart: '/wc/store/v1/cart',
  addItemToCart: (nonce: string) => `/wc/store/v1/cart/add-item?X-WC-Store-API-Nonce=${nonce}`,
  removeVipCartItem: (key: string) => `/wc/store/v1/cart/remove-item?key=${key}`,
  removeAllCartItems: `/wc/store/v1/cart/items`,
  createOrder: `/wc/v3/orders`,
  getVipOpportunities: '/wp/v2/opportunities?_fields=id,title,opportunity-category,acf.featured_image',
  sendRsvp: '/wp/v2/rsvp',
  logOut: '/wp/v2/logout',
  getVipRsvpEvents: (vipId: number) => `/wp/v2/vip-profiles/${vipId}/rsvp-events`,
  getAddresses: '/wp/v2/vip-profiles',
  deleteAddress: (vipId: number, addressId: number) => `/wp/v2/vip-profiles/${vipId}/addresses/${addressId}`,
  getVipOpportunityDetails: '/wp/v2/opportunities',
  orderFeedback: (vipId: number, orderNumber: number) => `/wp/v2/vip-profiles/${vipId}/orders/${orderNumber}/feedback`,
  eventFeedback: (vipId: number, eventId: number) => `/wp/v2/vip-profiles/${vipId}/events/${eventId}/feedback`,
  getWishlistItems: (vipId: number) => `/wp/v2/vip-profiles/${vipId}/wishlist`,
};

export { Endpoints };
